name: 'Microsoft Teams Incoming Webhook Notifications'
description: 'Sends a message to your Microsoft Teams channel using the MS Teams Webhook connector'
inputs:
  webhook:
    description: 'The webhook url for your Incoming Webhook connector'
    required: true
  title:
    description: 'A title for the card'
    required: true
  message:
    description: 'The message you want to send to your Microsoft Teams channel'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.webhook }}
    - ${{ inputs.title }}
    - ${{ inputs.message }}

branding:
  icon: 'mail'
  color: 'blue'
